### ISSUE TITLE
How to invoke jsesh for command-line rendering?

### ISSUE THREAD

**Issue by rillian** [tansebe/hr-st#6]
I'd like to automate document production from the various lines we're producing, but I haven't found a way to use jsesh on the command-line to render `.gly` files to images. Does anyone know how to do this?

**Comment by rillian** [comment]
Thanks! Looks like that's a hacked up version of `jsesh.demo.SimpleBitmap`. I was able to further modify it to convert `.gly` files to `png` images. I think we need to call something different to get `svg` or `pdf` output, but at least this is enough to get started!

**Comment by christiancasey** [comment]
Wait. I forgot about this. I did it with the hacked up one. Where is the code that does this directly?
If we can get a push-button png output, we can create a single "render" button for the entire site generation I made.

**Comment by rillian** [comment]
I [further hacked](https://github.com/rillian/jsesh/blob/MDCToPNG/jseshDemos/src/main/java/jsesh/demo/MDCToPNG.java) the `SimpleBitmap` and `jseshtext` classes to take a list of input files as arguments and convert them.

I suppose the next step is to package that somehow so we can automate `png_line` generation.
